# Generated by Django 3.0.7 on 2020-06-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200611_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='now_bid',
        ),
    ]
