# Generated by Django 3.0.7 on 2020-06-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_user_has_permit'),
        ('auction', '0005_remove_auction_now_bid'),
    ]

    operations = [
    ]
