# Generated by Django 3.0.7 on 2020-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20200614_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
