# Generated by Django 3.0.7 on 2020-06-17 09:08

import auction.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=auction.models.image_path1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winning_bid',
            field=models.IntegerField(default=0),
        ),
    ]
